# Generated by Django 5.2.8 on 2025-11-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('diagnostico_base', models.TextField(help_text='Hipótese ou diagnóstico (ex: F32.9 - Episódio depressivo não especificado).')),
                ('metas_longo_prazo', models.TextField(help_text='O que se espera alcançar no final do tratamento.')),
                ('metas_curto_prazo', models.TextField(help_text='Metas para as próximas sessões, alinhadas à Terapia Cognitivo Comportamental (TCC), por exemplo.')),
                ('tecnicas_abordagem', models.TextField(help_text='As principais técnicas e a abordagem teórica utilizada (ex: TCC, Psicanálise, Humanista).')),
                ('feedback_ia', models.TextField(blank=True, help_text='O resumo ou a revisão fornecida pela Inteligência Artificial.', null=True)),
            ],
        ),
    ]
