# Generated by Django 5.2.8 on 2025-11-29 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('contato_emergencia', models.CharField(blank=True, max_length=100, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'unique_together': {('usuario', 'nome_completo')},
            },
        ),
        migrations.CreateModel(
            name='DocumentacaoSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sessao', models.DateField()),
                ('anotacoes_brutas', models.TextField()),
                ('resumo_ia', models.TextField(blank=True, null=True)),
                ('sugestao_diagnostico', models.CharField(blank=True, max_length=255, null=True)),
                ('padroes_linguagem', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentacoes', to='psico_saas.paciente')),
            ],
            options={
                'verbose_name': 'Documentação da Sessão',
                'verbose_name_plural': 'Documentações das Sessões',
            },
        ),
        migrations.CreateModel(
            name='PlanoTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('diagnostico_base', models.TextField(help_text='Hipótese ou diagnóstico (ex: F32.9 - Episódio depressivo não especificado).')),
                ('metas_longo_prazo', models.TextField(help_text='O que se espera alcançar no final do tratamento.')),
                ('metas_curto_prazo', models.TextField(help_text='Metas para as próximas sessões, alinhadas à Terapia Cognitivo Comportamental (TCC), por exemplo.')),
                ('tecnicas_abordagem', models.TextField(help_text='As principais técnicas e a abordagem teórica utilizada (ex: TCC, Psicanálise, Humanista).')),
                ('feedback_ia', models.TextField(blank=True, help_text='O resumo ou a revisão fornecida pela Inteligência Artificial.', null=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='psico_saas.paciente')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TarefaExercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abordagem_teorica', models.CharField(choices=[('TCC', 'Terapia Cognitivo-Comportamental (TCC)'), ('PSICANALISE', 'Psicanálise'), ('HUMANISTA', 'Abordagem Humanista/Centrada na Pessoa'), ('OUTRA', 'Outra Abordagem')], max_length=50)),
                ('tema_principal', models.CharField(max_length=255)),
                ('detalhes_personalizacao', models.TextField(blank=True, null=True)),
                ('exercicio_ia', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='psico_saas.paciente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarefa/Exercício',
                'verbose_name_plural': 'Tarefas/Exercícios',
            },
        ),
    ]
