# Generated by Django 5.2.8 on 2025-11-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psico_saas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planotratamento',
            name='data_inicio_prevista',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
