# Generated by Django 5.2.8 on 2025-11-29 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psico_saas', '0002_planotratamento_data_inicio_prevista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planotratamento',
            name='metas_curto_prazo',
        ),
        migrations.RemoveField(
            model_name='planotratamento',
            name='metas_longo_prazo',
        ),
        migrations.RemoveField(
            model_name='planotratamento',
            name='tecnicas_abordagem',
        ),
        migrations.AddField(
            model_name='planotratamento',
            name='abordagem',
            field=models.TextField(default='Não Especificada', help_text='A abordagem teórica utilizada (ex: TCC, Psicanálise, Humanista).'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planotratamento',
            name='frequencia_sessoes',
            field=models.CharField(default='Semanal', help_text='Ex: Semanalmente, Quinzenalmente.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planotratamento',
            name='metas_tratamento',
            field=models.TextField(default='Metas de tratamento não especificadas na criação.', help_text='Metas a Longo e Curto Prazo (unificadas).'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planotratamento',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='psico_saas.paciente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planotratamento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
