# Generated by Django 5.2.8 on 2025-11-29 02:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psico_saas', '0003_remove_planotratamento_metas_curto_prazo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planotratamento',
            name='data_inicio_prevista',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início Prevista'),
        ),
    ]
