# Generated by Django 5.2.8 on 2025-11-29 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psico_saas', '0004_alter_planotratamento_data_inicio_prevista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoEducacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo_conteudo', models.CharField(choices=[('POST_REDES_SOCIAIS', 'Post para Redes Sociais'), ('TEXTO_CONSULTORIO', 'Texto para Consultório'), ('ARTIGO_BLOG', 'Artigo para Blog'), ('MATERIAL_PACIENTE', 'Material para Paciente')], max_length=50)),
                ('tema_principal', models.CharField(max_length=255)),
                ('publico_alvo', models.CharField(blank=True, max_length=100, null=True)),
                ('tom_voz', models.CharField(default='Profissional e acolhedor', max_length=100)),
                ('palavras_chave', models.TextField(blank=True, null=True)),
                ('conteudo_gerado', models.TextField(blank=True, null=True)),
                ('sugestoes_titulos', models.TextField(blank=True, null=True)),
                ('hashtags', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conteúdo Educacional',
                'verbose_name_plural': 'Conteúdos Educacionais',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
