# Generated by Django 5.2.8 on 2025-11-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psico_saas', '0005_conteudoeducacional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conteudoeducacional',
            options={},
        ),
        migrations.AddField(
            model_name='conteudoeducacional',
            name='sugestoes_imagens',
            field=models.TextField(blank=True, null=True),
        ),
    ]
